appmongo:
  image: mongo:3

backupmongo:
  image: mongo:3

opsmanager:
  image: rafaelsisweb/docker-opsmanager
  links:
    - appmongo:appmongo
    - backupmongo:backupmongo
  ports:
    - "18080:8080"
  environment:
    - OPSMANAGER_MONGO_APP=appmongo:27017
    - OPSMANAGER_BACKUPMONGO=backupmongo:27017
    - OPSMANAGER_CENTRALUR=YOUR_FQDN
    - OPSMANAGER_CENTRALURLPORT=YOUR_FQDN_PORT
